language: node_js
node_js:
  - "node"
script:
  - ./node_modules/.bin/eslint .
  - ./node_modules/.bin/ava --verbose tests\
deploy:
  provider: azure_web_apps
  username: LoginTestIsep
  password: Password
  site: http://bot-discord.azurewebsites.net
  verbose: true